### ISSUE TITLE
Cannot find the repo cloned with ``bender import``

### ISSUE THREAD

**Issue by znaky** [pulp-platform/bender#104]
I am running bender import to clone a repo that doesn't support bender. Everything looks good. It really seems like cloning it to /tmp and then checking out the correct commit. But I cannot locate the cloned repo afterwards. My ``Bender.yml`` looks like below. Am I missing something?
```
# Package metadata. Required.
package:
  # The name of the package. Required.
  name: my_package

# List of imported files from external repositories not supporting bender. Optional
external_import:
    # package name
  - name: my_external_repo
    # target directory
    target_dir: external/my_external_repo
    # upstream dependency (i.e. git repository similar to dependencies)
    upstream: { git: "ssh://git@code.mycompany.com/fpga/my_external_repo.git", rev: "224ace1221ebe16fec104c58250faa9f4eac84a2" }
```

FYI, when I add mapping, it just cannot find the files and errors out.
