### ISSUE TITLE
Bender import does not copy all files without any mapping entries

### ISSUE THREAD

**Issue by meggiman** [pulp-platform/bender#107]
My expectation was, that if I create an external import from a repository without specifying any mapping, that it would copy the entire repo structure as is. However, that doesn't seem to be the case. Without adding the dummy entry `{from: '', to: ''}` nothing is copied at all. Here is an entry to reproduce the issue:

``` yaml
external_import:
  - name: gpio
    target_dir: vendored_ips/gpio
    upstream: { git: "https://github.com/pulp-platform/gpio.git", rev: "add6f9f8218411a5dc6df524383e2d81695452d1"} #v0.1.1
```
