### ISSUE TITLE
Bender vendor support for upstream versions

### ISSUE THREAD

**Issue by colluca** [pulp-platform/bender#130]
Version 0.27.1 does not seem to support specifying `upstream` dependency revisions using the `version` attribute.

With the following `Bender.yml` contents:
```
vendor_package:
  - name: musl
    target_dir: sw/math
    upstream: { git: https://github.com/kraj/musl.git, version: 1.2.4 }
    include_from_upstream:
      - "src/math/tanh.c"
```
the `bender vendor init` command fails.

It succeeds when specifying the commit hash using the `revision` attribute:
```
vendor_package:
  - name: musl
    target_dir: sw/math
    upstream: { git: https://github.com/kraj/musl.git, rev: 7a43f6fea9081bdd53d8a11cef9e9fab0348c53d }
    include_from_upstream:
      - "src/math/tanh.c"
```

I found this comment to be a bit misleading:
https://github.com/pulp-platform/bender/blob/dc733b2c63f535efc24a08ee35adbc308f1946de/README.md?plain=1#L185
