### ISSUE TITLE
vendor_package files are not added as source

### ISSUE THREAD

**Issue by sazam0** [pulp-platform/bender#136]
following is my `vendor_package` settings:
```
vendor_package:
  - name: bextdep
    target_dir: vendor/bextdep
    upstream: { git: "https://github.com/cliffordwolf/bextdep.git", rev: "b96198514856bfaf85db3e7b0cb1d5f7e0c06d68" }
    include_from_upstream:
      - "bextdep.v"
      - "bextdep_pps.v"
```

`bender script vivado-sim -t rtl -t test` includes files from `sources` as expected but does not include the `bextdep.v` and `bextdep_pps.v`
