### ISSUE TITLE
`plugins:` will be deprecated?

### ISSUE THREAD

**Issue by mac-edmondson** [pulp-platform/bender#142]
Just now seeing this in the readme.
```yaml
# Format is the same as `dependencies` in a package manifest.
# DEPRECATED: This will be removed at some point.
plugins:
  additional-tools: { path: "/usr/local/additional-tools" }
```

Wondering if this is true and what the reasoning behind this is? I have found this feature quite useful. I have made packages which act as a means to run tooling via bender. For example, all of my components require a unit testing dependency that allows me to simply kick off a unit test, for any of my components, with something along the lines of `bender rtl_sim <args>`.  Anyway, I have found the feature quite useful and would be sad to see it go :(.
