### ISSUE TITLE
using environment variables in path dependencies

### ISSUE THREAD

**Issue by rbonthond** [pulp-platform/bender#144]
Would it be possible to use environment variables instead of relatives paths in Bender.yml for package path dependencies? We're trying to re-use some things between different projects with different layouts, and being able to use environment variables would make this much more flexible.

```
package:
    name: A

dependencies:
   B: {path: "$WORKSPACE/B"}

sources:
  - files:
    - a.txt

```
