### ISSUE TITLE
Package with only include_dirs doesn't work

### ISSUE THREAD

**Issue by msmithTT** [pulp-platform/bender#161]
I have a package that just contains include files (global files that define parts of a larger project).  If I attempt to create a Bender file for this, for example:

```
package:
  name: my_package
  authors:
    - "My Name"

sources:
  include_dirs:
    - rtl

  files:
```

This doesn't generate any +incdir+ command-line options.

If I add a single dummy file to this, then it adds the required +incdir+ command-line options as well as the dummy file:

```
package:
  name: my_package
  authors:
    - "My Name"

sources:
  include_dirs:
    - rtl

  files:
    - rtl/empty_dummy_module.sv
```

**Comment by micprog** [comment]
I think you may be looking for the `export_include_dirs` functionality.

**Comment by msmithTT** [comment]
Thanks for the hint, but unfortunately doesn't make a difference.

Using this Bender file:

```
sources:
  export_include_dirs:
    - rtl

  files:
```

Then running 'bender script flist' it returns an empty string.
